services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: api_productos_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysqljavier
      MYSQL_DATABASE: db_productos
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - api_network

  # Aplicación Django
  web:
    build: .
    container_name: api_productos_django
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-3z1f9y-@3*1=m7h-1zzp4kci=6nk1=b))1elb+xt6x0fv%o
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db_productos
      - DB_USER=api_user
      - DB_PASSWORD=api_password
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - api_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # phpMyAdmin para gestión de base de datos (opcional)
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: api_productos_phpmyadmin
  #   restart: unless-stopped
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     PMA_USER: api_user
  #     PMA_PASSWORD: api_password
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - api_network

volumes:
  mysql_data:

networks:
  api_network:
    driver: bridge
