# Generated by Django 5.2.6 on 2025-09-25 21:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del producto', max_length=200, verbose_name='Nombre del producto')),
                ('categoria', models.CharField(help_text='Categoría a la que pertenece el producto', max_length=100, verbose_name='Categoría')),
                ('marca', models.CharField(help_text='Marca del producto', max_length=100, verbose_name='Marca')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del producto en la moneda base', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad disponible en inventario', verbose_name='Cantidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['categoria'], name='productos_p_categor_15e07f_idx'), models.Index(fields=['marca'], name='productos_p_marca_39a282_idx'), models.Index(fields=['precio'], name='productos_p_precio_d043df_idx')],
            },
        ),
    ]
